baseURL = 'https://www.andyferris.au/'
languageCode = 'en-us'
title = "Andy Ferris"
theme = "hugo-coder"

paginate = 20

pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
  background_color = "#357EDD"
  author = "Andy Ferris"
  description = "Personal blog of Andy Ferris"
  info = "Computers and math for fun and profit"
  avatarurl = "images/avatar.png"
  keywords = "blog,developer,maths,science,programming,personal"
  since = 2022
  enableTwemoji = true
  customCSS = ["css/custom.css"]

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/andyferris/"
[[params.social]]
  name = "Linked In"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/andrewjamesferris/"
[[params.social]]
  name = "University of Queensland"
  icon = "fa fa-graduation-cap fa-2x"
  weight = 1
  url = "https://courses.smp.uq.edu.au/MATH2504/"
[[params.social]]
  name = "ELARA AI"
  icon = "fa fa-industry fa-2x"
  weight = 1
  url = "https://elaraai.com/"

# Menus
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Projects"
  weight = 1
  url  = "projects/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"
